# -*- coding: utf-8 -*-
"""bayesian_network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cCR6R5Rdkh8aWCmTLYbpvWA_h-fW0iUA
"""

!pip install pgmpy
import numpy as np
import pandas as pd
import csv
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.models import BayesianModel
from pgmpy.inference import VariableElimination

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('heart.csv')
df = df.replace('?',np.nan)

df.head()

df['heartdisease'].unique()



df.columns

model = BayesianModel([('age','heartdisease'),('gender','heartdisease'),('exang','heartdisease'),('cp','heartdisease'),('heartdisease','restecg'),('heartdisease','chol')])
model.fit(df,estimator=MaximumLikelihoodEstimator)

heart_diesease_infer = VariableElimination(model)

print('\n 1. Probability of HeartDisease given evidence= restecg')
q1 = heart_diesease_infer.query(variables=['heartdisease'],evidence={'restecg':1})
print(q1)

print('\n 2. Probability of HeartDisease given evidence= cp ')
q2 = heart_diesease_infer.query(variables=['heartdisease'],evidence={'cp':2})
print(q2)















