# -*- coding: utf-8 -*-
"""email_spam_filter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g74-pI_Cq3AQ7KxGB9q4nNtyfATpXY9M
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv('spam.csv')

df.head()

df.columns

df.isnull().sum()

df['Spam'] = df['Category'].apply(lambda x:1 if x=='spam' else 0)

df.head(2)

df.drop(['Category'],axis=1,inplace=True)

df.head(2)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Spam, test_size=0.25)

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

clf.fit(X_train,y_train)

emails = [
    'Hey Sonu!, Are you home now?',
    'Finale Days ends 10th Nov! Sale sale sale!'
]

clf.predict(emails)

clf.score(X_test,y_test)

